### ISSUE TITLE
Navigator is not defined

### ISSUE THREAD

**Issue by Tixyel** [aarondail/react-zoomable-ui#57]

**Comment by jorgegonzalez** [comment]
Getting the same error. App just crashes with `Navigator is not defined` when wrapping some components with `Space` in a NextJS app

**Comment by DovahBrownies** [comment]
This should fix it:
#58 

But I don't know how active the owner is.

Also it's worth noting that this issue ONLY occurs on mobile views because `navigator` is being invoked to check what kind of mobile client is accessing your webpage. Maybe you can leverage some of Next's built-in optimizations - [Like `next/dynamic`](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr).

**Comment by parrvvv** [comment]
I solved it using `"use client"` in NextJS.

**Comment by DovahBrownies** [comment]
> I solved it using `"use client"` in NextJS.

I'm pretty sure you'll still get the error in your console, though... Right?

**Comment by parrvvv** [comment]
You are right, the error is still present in console. And looks like it's not working as well.
